### ISSUE TITLE
Password protect qa.merative.com and stage.merative.com

### ISSUE THREAD

**Issue by keith-kaplan** [hlxsites/merative2#190]
On AEM pages we have password protected our lower environments. Here are some examples:
https://stage.merative.com/clinical-decision-support
https://stage.merative.com/clinical-development

We would like to implement the same method for all AEM Franklin pages on the following environments:
stage.merative.com
qa.merative.com

**Comment by helms-charity** [comment]
It looks like stage.merative.com and qa.merative.com are pointing to the ".live" Franklin pages. Since we don't have a concept of a staging and QA environment, I'm thinking we could point to the ".page" Franklin pages as a first step. 
Then we can look at limiting access, possibly at the CDN level -- I will consult with @amol-anand after the long weekend.
