### ISSUE TITLE
[Article/Blog]: Adjust placement of Authors and Published date

### ISSUE THREAD

**Issue by proeung** [hlxsites/merative2#236]
## Problems/Motivation
- This is a follow-up ticket to the issue that we've discovered within this PR (https://github.com/hlxsites/merative2/pull/217#pullrequestreview-1466089486).

## Proposed Solution
- Implement the new design treatment based on the exploration made by [Sachin Madan Meshram (Contractor)](https://jira.wh-sdlc.watson-health.ibm.com/secure/ViewProfile.jspa?name=smeshram%40merative.com) 
- Keep the author's position below the image, but move "Published on" and "Read Time" to be above the image and right below the tags.

## Design Specs:
- Figma - https://www.figma.com/file/FSqQ1LYrVSssEFOZuOnMIE/Final-page-layouts-for-Merative.com?type=design&node-id=1262%3A48026&t=1Mwvay3X03mn5gPt-1 

![Article hero - desktop](https://github.com/hlxsites/merative2/assets/1815714/a12074ed-786a-4935-b659-6b0d968c4b64)

Corresponding JIRA ticket
- https://jira.wh-sdlc.watson-health.ibm.com/browse/MERATIVE-760

**Comment by proeung** [comment]
@helms-charity For this particular change in the design where we're looking to place the "Published Date" and "Read Time" above the image. It looks to me like we should insert a block (eg. `pub-metadata`), similar to what we have implemented for the `author-bio`. However, this direction means we must go into every blog page and update the placement, which is not too bad since we don't have a lot of published blog pages.

Another solution is to append the "Published Date" and "Read Time" metadata above the image if it exists, but that feels a bit hacky because what if we have a blog post without a picture? I'm open to suggestions on how to best achieve this.

**Comment by helms-charity** [comment]
Ask your team if there will be a case where there is no picture? 
I recall Keith saying there would always be one. I think this can be solved without editing all the pages.

**Comment by amol-anand** [comment]
Most of this page is "Auto blocked" which means we basically insert the breadcrumb, left nav, tags etc.. in automatically without the author having to do anything other than the content. 

Currently the Published Date and Read Time are part of the author bio block, so we can move that functionality and auto block it here instead https://github.com/hlxsites/merative2/blob/9498ab68e1c237d9db38defa2e15540ae2b9da1b/scripts/scripts.js#L182-L183 you can look at how we add the breadcrumb and left nav and use the same approach to add the pub-metadata stuff to the blog pages.

Regarding no picture:
If you find a picture, put it before the picture
if there is no picture, then put it after the title? 

So now, you might ask why do we have author-bio as a block? I think initially it was kept as a block so that authors could control where it went, but it's been many months and I haven't seen it move once. It is a prime candidate to be auto blocked as well.
